<!-- A supprimer -->
<?php echo $this->partial('/partials/common-form-js.phtml'); ?>

<div id='form_action' class="panel panel-default">
	<div class="panel-heading">
		<?php echo $this->translate('Bank statement', 'ppit-accounting', $context->getLocale()).': '.$this->translate('Add a book entry', 'ppit-accounting', $context->getLocale()) ?>
 		<div class="btn-group pull-right">
			<?php echo $this->partial('/partials/action-widget.phtml', array(
					'context' => $context,
					'target' => 'form_action',
					'id' => 'update-remove-anchor',
					'glyphicon' => 'glyphicon-remove',
					'class' => 'index-btn',
					'title' => $this->translate('Return to list', 'ppit-core', $context->getLocale()),
			)) ?>
		</div>
	</div>
    <div class="panel-body">

		<!-- Form header -->
		<?php echo $this->partial('/partials/form-header', array(
					'update_time' => $journal->update_time,
					'message' => $message,
					'error' => $error,
					'csrfForm' => $csrfForm,
					'context' => $context,
		));
		$properties = array();
		?>

		<?php if ($message == 'OK') $isDisabled = true; else $isDisabled = false; ?>
	
<!-- Operation date -->
		<?php
			echo $this->partial('/partials/date-widget.phtml', array(
				'property' => 'operation_date',
				'label' => '* '.$this->translate('Operation date', 'ppit-accounting', $context->getLocale()),
				'value' => $journal->operation_date,
				'isMandatory' => true,
				'context' => $context,
				'isDisabled' => $isDisabled,
		));
		$properties['operation_date'] = 'input';
		?>
		
<!-- Reference -->
		
		<?php
			echo $this->partial('/partials/input-widget.phtml', array(
				'property' => 'reference',
				'label' => '* '.$this->translate('Reference', 'ppit-accounting', $context->getLocale()),
				'value' => $journal->reference,
				'isMandatory' => true,
				'maxLength' => 255,
				'context' => $context,
				'isDisabled' => $isDisabled,
		));
		$properties['reference'] = 'input';
		?>
		
<!-- Caption -->
		<?php
			echo $this->partial('/partials/input-widget.phtml', array(
				'property' => 'caption',
				'label' => '* '.$this->translate('Caption', 'ppit-core', $context->getLocale()),
				'value' => $journal->caption,
				'isMandatory' => true,
				'maxLength' => 255,
				'context' => $context,
				'isDisabled' => $isDisabled,
		));
		$properties['caption'] = 'input';
		?>

		<div>&nbsp;</div>

<!-- Direction -->
		<?php
			echo $this->partial('/partials/select-widget.phtml', array(
				'property' => 'direction_0',
				'label' => $this->translate('Direction', 'ppit-accounting', $context->getLocale()),
				'modalities' => array('-1' => $this->translate('Debit', 'ppit-accounting', $context->getLocale()), '1' => $this->translate('Credit', 'ppit-acounting', $context->getLocale())),
				'value' => (array_key_exists(0, $journal->rows)) ? $journal->rows[0]['direction'] : '',
				'isMandatory' => false,
				'context' => $context,
				'isDisabled' => $isDisabled,
		));
		$properties['direction_0'] = 'select';
		?>
		
<!-- Amount -->
		<?php
			echo $this->partial('/partials/number-widget.phtml', array(
				'property' => 'amount_0',
				'label' => $this->translate('Amount', 'ppit-core', $context->getLocale()),
				'value' => (array_key_exists(0, $journal->rows)) ? $context->formatFloat($journal->rows[0]['amount'], 2) : '',
				'isMandatory' => false,
				'min' => 0,
				'max' => 999999,
				'context' => $context,
				'isDisabled' => $isDisabled,
		));
		$properties['amount_0'] = 'input';
		?>

<!-- Account -->
		<input type="hidden" id="account_0" name="account_0" value="512" />
		<?php
		$properties['account_0'] = 'hidden';
		?>

<?php if ($message == 'OK') : ?>

<!-- Foot return link -->
		<div class="form-group" id="foot_return_link">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<?php echo $this->partial('/partials/action-widget.phtml', array(
						'context' => $context,
						'target' => 'form_action',
						'id' => 'update-foot-return-anchor',
						'class' => 'index-btn',
						'text' => $this->translate('Close', 'ppit-core', $context->getLocale()),
				)) ?>
			</div>
		</div>

<?php else : ?>

<!-- Submit button -->
	    <div class="form-group">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<input name="submit" type="submit" id="update-submit-button" class="btn btn-warning" value="<?php echo $this->translate('Confirm', 'ppit-core', $context->getLocale()) ?>">
				&nbsp;&nbsp;
				<?php echo $this->partial('/partials/action-widget.phtml', array(
						'context' => $context,
						'target' => 'form_action',
						'id' => 'update-cancel-anchor',
						'class' => 'index-btn',
						'text' => $this->translate('Cancel', 'ppit-core', $context->getLocale()),
				)) ?>
			</div>
		</div>

<?php endif;?>

	</div>
</div>

<script id="journal/bankStatement-script">

// Return to list
eval(document.getElementById('update-remove-anchor-script').innerHTML);

<?php if ($message == 'OK') : ?>

	eval(document.getElementById('update-foot-return-anchor-script').innerHTML);

<?php else : ?>

	eval(document.getElementById('update-cancel-anchor-script').innerHTML);

	// Submit
	<?php
	echo $this->partial('/partials/form-script', array(
			'context' => $context,
			'formRoute' => $this->url('journal/bankStatement', array('id' => $id)),
			'formScript' =>'journal/bankStatement-script',
			'properties' => $properties,
/*			'mainRoute' => $this->url('journal/index'),
			'mainScript' =>'journal/index-script',
			'hideForm' => false,*/
	)) ?>

<?php endif;?>

</script>
