<!-- 
/**
 * PpitCore V1.0 (https://github.com/p-pit/PpitCore)
 *
 * @link      https://github.com/p-pit/PpitCore
 * @copyright Copyright (c) 2016 Bruno Lartillot
 * @license   https://github.com/p-pit/PpitCore/blob/master/license.txt GNU-GPL license
 */
-->

<?php
$title = $context->getConfig('journal/index')['title'][$context->getLocale()];
$this->headTitle($title);
echo $this->partial('/partials/header');
?>
  
  <div>&nbsp;</div>
  
  <div class="row" id="main_menu" >
    <div class="col-md-10 col-md-offset-1">
      <div align="center">

<?php foreach ($context->getConfig('menus/p-pit-finance')['entries'] as $entryId => $entryDef) : ?>
  <?php if ($context->isAllowed($entryDef['route'])) : ?>
        <button type="button" class="btn btn-default menu-btn" id="<?php echo $entryId ?>-anchor">
    <?php if (array_key_exists('glyphicon', $entryDef)) : ?>
          <span class="glyphicon <?php echo $entryDef['glyphicon'] ?>"></span>
    <?php endif;?>
          <?php echo $entryDef['label'][$context->getLocale()] ?>
        </button>
  <?php endif ?>
<?php endforeach;?>

      </div>
      <div>&nbsp;</div>
    </div>
  </div>

  <!-- Main panel -->
  <div class="row">
    <div class="col-md-12 ppit-panel" id="index_action"></div>

<div class="panel panel-default">
  <div class="panel-heading" style="background: <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
	<strong><?php echo $this->translate('Bank statement', 'ppit-accounting', $context->getLocale()) ?></strong>
  </div>
  <div class="panel-body">

<!-- Actions -->
  <div>
    <a type="button" class="btn btn-default" href="<?php echo $this->url('journal/qonto') ?>">
      <span class="glyphicon glyphicon-cloud-download"></span>
      <span><?php echo $this->translate('Actualize from bank', 'ppit-accounting', $context->getLocale()) ?></span>
    </a>
  </div>
  <div>&nbsp;</div>

<!-- Form header -->
<form action="" id="ppit-form" method="post" class="form-horizontal" enctype="multipart/form-data">
			
<!-- Global message -->
<?php if ($message == 'OK') : ?>
	<div id="message">
			<div class="alert alert-success"><h4><?php echo $this->translate('Your request has been registered', 'ppit-core', $context->getLocale()) ?></h4></div>
	</div>
<?php endif;?>

<?php 
if ($message == 'OK') $isDisabled = true; else $isDisabled = false;
?>

<div style="overflow-x:auto;">
  <table class="table table-striped ppit_index">
  <tr>

<?php foreach ($context->getConfig('bank_statement/list')['properties'] as $propertyId => $unused) : ?>
  <?php 
  $property = $context->getConfig('accounting_operation')['properties'][$propertyId];
  if ($property['type'] == 'specific') $property = $context->getConfig($property['definition']);
  ?>
  <?php if ($property) : ?>
    <th align="center">
      
      <?php $label = (array_key_exists('short', $property)) ? $property['short'][$context->getLocale()] : $property['labels'][$context->getLocale()] ?>
    <?php if ($label) : ?>
      <button type="button" class="btn btn-default btn-xs ppit-sort-anchor" id="<?php echo $propertyId ?>-anchor">
        <span><?php echo ($propertyId == 'sequence') ? $this->translate('Reconciliate', 'ppit-accounting', $context->getLocale()) : $label ?></span>
      <?php if ($major == $propertyId) : ?>
        <span class="glyphicon glyphicon-triangle-<?php echo ($dir == 'ASC') ? 'top' : 'bottom' ?>"></span>
      <?php endif ?>
      </button>
    <?php endif;?>
    </th>
  <?php endif;?>
<?php endforeach;?>
  </tr>

<?php $i = 0; foreach ($transactions as $transaction) : ?>
  <?php 
  $amount = $transaction->amount;
  if ($transaction->direction == -1) $amount *= -1;
  ?>
  
  <tr class="operation">
 
  <?php foreach ($context->getConfig('bank_statement/list')['properties'] as $propertyId => $unused) : ?>
    <?php 
    $property = $context->getConfig('accounting_operation')['properties'][$propertyId];
    if ($property['type'] == 'specific') $property = $context->getConfig($property['definition']);
    ?>
    <?php if ($property) : ?>
  
      <?php if ($propertyId == 'sequence') : ?>
    <td>
    <?php $minGap = 40; $matchables = []; $matched = null; foreach ($operations as $operation) : ?>
        <?php 
        $total_amount = $operation->properties['total_amount'];
        if ($operation->properties['direction'] == -1) $total_amount *= -1;
        if ($amount == $total_amount) {
          $matchables[] = $operation;
          if ($transaction->sequence == $operation->properties['sequence']) $matched = $operation; 
	      else {
            $gap = abs(date_diff(date_create($operation->properties['operation_date']), date_create($transaction->operation_date))->days);
            if ($gap < $minGap) {
            	$matched = $operation;
            	$minGap = $gap;
            }
	      }
        }
        ?>
    <?php endforeach;?>
    <?php if (count($matchables) == 0) : ?>
      <?php echo $this->translate('Nothing to match', 'ppit-accounting', $context->getLocale())?>
    <?php else : ?>
      <select class="form-control" name="sequence-<?php echo $transaction->reference ?>" <?php if ($transaction->status == 'matched') : ?>disabled="disabled"<?php endif;?>>
        <option><?php echo $this->translate('Please choose', 'ppit-core', $context->getLocale()) ?></option>
      <?php foreach ($matchables as $matchable) : ?>
        <?php 
        $total_amount = $matchable->properties['total_amount'];
        if ($matchable->properties['direction'] == -1) $total_amount *= -1;
        ?>
        <option value="<?php echo $matchable->properties['sequence'] ?>" <?php if ($matched == $matchable) : ?>selected<?php endif;?>><?php echo $matchable->properties['sequence'] . ' | ' . $matchable->properties['caption'] . ' | ' . $matchable->properties['operation_date'] . ' | ' . $total_amount ?>
      <?php endforeach;?>
      </select>
    <?php endif; ?>
    </td>
  
      <?php elseif ($propertyId == 'amount') : ?>
    <td style="text-align: right"><?php echo (($transaction->direction == -1) ? '-' : '') . $context->formatFloat($transaction->amount, 2) . '&nbsp;' .  $transaction->currency ?></td>
  
      <?php elseif ($property['type'] == 'date') : ?>
    <td><?php echo $context->decodeDate($transaction->properties[$propertyId]) ?></td>

      <?php elseif ($property['type'] == 'number') : ?>
    <td style="text-align: right"><?php echo $context->formatFloat($transaction->properties[$propertyId], 2) ?></td>

      <?php elseif ($property['type'] =='select') : ?>
    <td><?php if ($transaction->properties[$propertyId]) echo $property['modalities'][$transaction->properties[$propertyId]][$context->getLocale()] ?></td>

      <?php else : ?>
    <td><?php echo $transaction->properties[$propertyId] ?></td>

      <?php endif;?>

    <?php endif;?>
  <?php endforeach;?>
  </tr>
  
<?php endforeach; ?>
  <tr>
    <th colspan="<?php echo count($context->getConfig('bank_statement/list')['properties']) + 1 ?>" style="text-align: center">
<?php 
$property = $context->getConfig('accounting_operation')['properties'][$major];
if ($property['type'] == 'specific') $property = $context->getConfig($property['definition']);
?>
      <?php echo $property['labels'][$context->getLocale()] ?>&nbsp;&nbsp;&nbsp;&nbsp;
      <?php echo $this->translate('Number', 'ppit-core', $context->getLocale()) ?>: <?php echo $count ?>&nbsp;&nbsp;&nbsp;&nbsp;
      <?php if ($sum) echo $this->translate('Sum', 'ppit-core', $context->getLocale()).': '.$sum ?>&nbsp;&nbsp;&nbsp;&nbsp;
      <?php if ($average) echo $this->translate('Average', 'ppit-core', $context->getLocale()).': '.$average ?>

<?php if ($distribution) : ?>
      <select id="select-distribution">
  <?php foreach ($distribution as $modality => $value) : ?>
        <option value="<?php echo $modality ?>"><?php echo $property['modalities'][$modality][$context->getLocale()] ?></option>
  <?php endforeach;?>
      </select>
      &nbsp;&nbsp;
  <?php foreach ($distribution as $modality => $value) : ?>
      <span class="distribution" id="distribution_<?php echo $modality ?>"><?php echo $value ?> / <?php echo $count ?> = <?php echo round($value / $count * 100, 1) ?>%</span>
  <?php endforeach;?>
<?php endif;?>
    </th>
  </tr>

</table>

<?php if ($message != 'OK') : ?>
    <div class="form-group">
		<div class="col-sm-5">&nbsp;</div>
		<div   class="col-sm-7">
			<input type="submit" class="btn btn-warning" value="<?php echo $this->translate('Submit', 'ppit-core', $context->getLocale()) ?>">
		</div>
	</div>
<?php endif;?>
	</div>
</form>
        
      </div>
    </div>
  </div>

<script>

<?php foreach ($context->getConfig('menus/p-pit-finance')['entries'] as $entryId => $entryDef) : ?>
$('#<?php echo $entryId ?>-anchor').click(function () { $(location).attr('href', '<?php echo $this->url($entryDef['route'], $entryDef['params']) ?>'); });
<?php endforeach;?>

</script>
