
		<!-- Form header -->
		<?php echo $this->partial('/partials/form-header', array(
					'update_time' => $journal->update_time,
					'message' => $message,
					'error' => $error,
					'csrfForm' => $csrfForm,
					'context' => $context,
		));
		?>

		<div class="form-group">
			<div class="col-sm-5">&nbsp;</div>
			<div class="col-sm-7">
				<input name="submit" type="submit" id="submit-button" class="btn btn-warning" value="<?php echo $this->translate('Add', 'ppit-core', $context->getLocale()) ?>">
			</div>
		</div>
		
		<?php if ($message == 'OK') $isDisabled = true; else $isDisabled = false; ?>
	
<!-- Operation date -->
		<?php
			echo $this->partial('/partials/date-widget.phtml', array(
				'property' => 'operation_date',
				'label' => '* '.$this->translate('Operation date', 'ppit-accounting', $context->getLocale()),
				'value' => $journal->operation_date,
				'isMandatory' => true,
				'context' => $context,
				'isDisabled' => $isDisabled,
		));
		?>
		
<!-- Reference -->
		
		<?php
			echo $this->partial('/partials/input-widget.phtml', array(
				'property' => 'reference',
				'label' => '* '.$this->translate('Reference', 'ppit-accounting', $context->getLocale()),
				'value' => $journal->reference,
				'isMandatory' => true,
				'maxLength' => 255,
				'context' => $context,
				'isDisabled' => $isDisabled,
		));
		?>
		
<!-- Caption -->
		<?php
			echo $this->partial('/partials/input-widget.phtml', array(
				'property' => 'caption',
				'label' => '* '.$this->translate('Caption', 'ppit-core', $context->getLocale()),
				'value' => $journal->caption,
				'isMandatory' => true,
				'maxLength' => 255,
				'context' => $context,
				'isDisabled' => $isDisabled,
		));
		?>
	    
<!-- Proof -->
		<div class="form-group" id="proof_id_group">
			<label class="col-sm-5 control-label"><?php echo $this->translate('Proof', 'ppit-accounting', $context->getLocale())?></label>
			<div class="col-sm-7">
				<input type="file" name="proof_id" id="proof_id" class="form-control" />
			</div>
		</div>
		<?php 
		?>
		
<!-- Bank denoting -->
		<?php
			$modalities = array();
			foreach ($journal->availableBankJournalEntries as $entry) $modalities[$entry->id] = $entry->caption.' ('.$context->decodeDate($entry->operation_date).') : '.$context->formatFloat($entry->amount, 2);
			echo $this->partial('/partials/select-widget.phtml', array(
				'property' => 'bank_journal_reference',
				'label' => $this->translate('Bank journal reference', 'ppit-accounting', $context->getLocale()),
				'modalities' => $modalities,
				'value' => $journal->bank_journal_reference,
				'isMandatory' => false,
				'maxLength' => 255,
				'context' => $context,
				'isDisabled' => $isDisabled,
		));
		?>
		
<?php for ($i = 0; $i < 10; $i++) : ?>

		<div>&nbsp;</div>

<!-- Direction -->
		<?php
			echo $this->partial('/partials/select-widget.phtml', array(
				'property' => 'direction_'.$i,
				'label' => $this->translate('Direction', 'ppit-accounting', $context->getLocale()),
				'modalities' => array('-1' => $this->translate('Debit', 'ppit-accounting', $context->getLocale()), '1' => $this->translate('Credit', 'ppit-acounting', $context->getLocale())),
				'value' => (array_key_exists($i, $journal->rows)) ? $journal->rows[$i]['direction'] : '',
				'isMandatory' => false,
				'context' => $context,
				'isDisabled' => $isDisabled,
		));
		?>
		
<!-- Amount -->
		<?php
			echo $this->partial('/partials/number-widget.phtml', array(
				'property' => 'amount_'.$i,
				'label' => $this->translate('Amount', 'ppit-core', $context->getLocale()),
				'value' => (array_key_exists($i, $journal->rows)) ? $context->formatFloat($journal->rows[$i]['amount'], 2) : '',
				'isMandatory' => false,
				'min' => 0,
				'max' => 999999,
				'context' => $context,
				'isDisabled' => $isDisabled,
		));
		?>

<!-- Direction -->
		<?php
			$modalities = array();
			foreach ($config['ppitAccountingSettings']['accounts'] as $accountId => $account) {
				$modalities[$accountId] = $accountId.' - '.$account['caption'];
			}
			echo $this->partial('/partials/select-widget.phtml', array(
				'property' => 'account_'.$i,
				'label' => $this->translate('Account', 'ppit-accounting', $context->getLocale()),
				'modalities' => $modalities,
				'value' => (array_key_exists($i, $journal->rows)) ? $journal->rows[$i]['account'] : '',
				'isMandatory' => false,
				'context' => $context,
				'isDisabled' => $isDisabled,
		));
		?>

<?php endfor;?>

