<style>

table.account {
	font-size:0.9em; 
	border-width:1px; 
 	border-style:solid; 
	border-color:gray;
}
table.account caption { 
	padding:1em 0 0.5em 1em;
}
table.account th {
	font-weight: bold;
	border-width:1px; 
 	border-style:solid; 
	border-color:gray;
	background-color:#DDD;
	text-align: center;
}

table.account td.value {
	text-align: right;
}

table.account tfoot {
	font-weight: bold;
	border-width:1px; 
 	border-style:solid; 
	border-color:gray;
	background-color:#EEE;
}
</style>

<div class="row">
    <div class="col-md-12">

		<div class="panel panel-default">
			<div class="panel-heading">
				<strong>
					<?php echo $this->translate('General ledger', 'ppit-accounting', $context->getLocale()).' '.$account->year ?>  -
					<?php echo $config['ppitAccountingSettings']['accounts'][$account->account]['caption']?>
					(<?php echo $account->account ?>)
				</strong>
			</div>
			<div class="panel-body">
				<table class="table table-striped account">
					<thead>
						<tr>
							<th><?php echo $this->translate('Journal', 'ppit-accounting', $context->getLocale())?></th>
							<th><?php echo $this->translate('Sequence', 'ppit-accounting', $context->getLocale())?></th>
							<th><?php echo $this->translate('Operation date', 'ppit-accounting', $context->getLocale())?></th>
							<th><?php echo $this->translate('Accounting date', 'ppit-accounting', $context->getLocale())?></th>
							<th><?php echo $this->translate('Reference', 'ppit-accounting', $context->getLocale())?></th>
							<th><?php echo $this->translate('Caption', 'ppit-accounting', $context->getLocale())?></th>
							<th><?php echo $this->translate('Debit', 'ppit-accounting', $context->getLocale())?></th>
							<th><?php echo $this->translate('Credit', 'ppit-accounting', $context->getLocale())?></th>
							<th>&nbsp;</th>
							<th>&nbsp;</th>
						</tr>
					</thead>
<?php foreach ($account->rows as $row) : ?>
					<tr>
						<td><?php echo $row->journal_code ?></td>
						<td class="value"><?php echo $row->sequence ?></td>
						<td><?php echo $context->decodeDate($row->operation_date) ?></td>
						<td><?php echo $context->decodeDate($row->accounting_date) ?></td>
						<td><?php echo $row->reference ?></td>
						<td><?php echo $row->caption ?></td>
						<td class="value"><?php echo $context->formatFLoat($row->debit_amount, 2) ?></td>
						<td class="value"><?php echo $context->formatFLoat($row->credit_amount, 2) ?></td>
						<td><input type="checkbox" /></td>
						<td>
	<?php if ($row->proof_id) : ?>
							<a class="glyphicon glyphicon-cloud-download" href="<?php echo $this->url('document/download', array('id' => $row->proof_id)) ?>" target="_blank" title="<?php echo $this->translate('Proof', 'ppit-accounting', $context->getLocale()) ?>"/>
	<?php endif; ?>
						</td>
					</tr>
<?php endforeach;?>
					<tfoot>
						<tr>
							<td colspan="6" style="text-align: right"><?php echo $this->translate('Sum', 'ppit-accounting', $context->getLocale()) ?></td>
							<td class="value"><?php echo $context->formatFLoat($account->debit_sum, 2) ?></td>
							<td class="value"><?php echo $context->formatFLoat($account->credit_sum, 2) ?></td>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td colspan="6" style="text-align: right"><?php echo $this->translate('Balance', 'ppit-accounting', $context->getLocale()) ?></td>
							<td class="value"><?php echo $context->formatFLoat($account->debit_balance, 2) ?></td>
							<td class="value"><?php echo $context->formatFLoat($account->credit_balance, 2) ?></td>
							<td>&nbsp;</td>
							<td>&nbsp;</td>
						</tr>
					</tfoot>
				</table>

			</div>
		</div>
	